doc/vectorscope.md
src/vectorscope.c

Previously skintone started from the center, which was not easy to find
where is the center. The new graticule is good to find the center.
The start point of the skintone is 0.5 pixel moved to make it same
location as the new I-Q lines.

vectorscope: Add I-Q lines and set it as the default

---

src/scope-widget-properties.cpp
src/scope-widget-properties.hpp
src/scope-widget.cpp
src/scope-widget.hpp

This PR includes some small improvements in user experiences on the Scope Dock.
- Open the property tab that the user make right-click.
- Drag and drop is not interrupted even if the cursor goes to outside the ROI.
- Suppress messages when resizing Scope Dock.

dock Improve UI

---

src/common.c
src/common.h
src/histogram.c
src/roi.c
src/roi.h
src/scope-widget.cpp
src/vectorscope.c
src/waveform.c

Just after booting OBS Studio with Scope Dock, a thread `com.apple.main-thread` crashes at `__gl_update_block_invoke` from `libobs-opengl.so`.
Tested OS: macOS 10.11.6 + OBS Studio 26.1.2
Also the same error was reported on macOS 10.15.7.

dock: Fix crash when starting with Scope Dock

---

src/common.h
src/histogram.c
src/roi.c
src/vectorscope.c
src/waveform.c

Temporarily set colorspace of ROI from vectorscope.
The colorspace property in other sources are disabled if the target is ROI.
Fix #26.

roi: Fix colorspace setting

---

src/scope-dock.cpp
src/scope-dock.hpp

When switching scene-collection, old dock instances are not removed. It causes the number of dock instances to increase exponentially.

dock: Fix scene-collection change to remove old docks

---

CMakeLists.txt
README.md
doc/dock.md
src/scope-dock-new-dialog.cpp
src/scope-dock-new-dialog.hpp
src/scope-dock.cpp
src/scope-dock.hpp

The flow to open and close the dock is revised.
- When a user closed the dock widget, the instance will be deleted, where previously it was just hidden.
- Due to above change, the user cannot find the lagacy way (`View` -> `Docks` -> `Scope: program`) to open the dock once the user closed the dock.
- When opening the dock, user can navigate `Tools` and `New Scope Dock...` from the menu and user can create any number of docks.
- In addition, user can select target source of the scope dock.

dock: Revise open and close of docks

---

src/roi.c

When YUV is not selected, metadata for stage-surface is not updated, which causes these problems on waveform and histogram.
- When YUV is not selected from the startup, nothing is displayed.
- When the component type is switched or vectorscope is disabled during
runtime, waveform and histogram stop following the ROI selection.
This PR also fixes issue #39.

roi: Fix not updated stage-surface information

---

src/scope-dock-new-dialog.cpp
src/scope-dock.cpp

There was an incorrect conversion from QString to UTF-8.
The bug was reported on the forum: https://obsproject.com/forum/threads/obs-color-monitor.143375/post-538366

dock: Fix titile cannot be set on Windows

---

src/scope-dock.cpp

If the dock target is not program, dock will be initially shown on the left.

dock: Put dock on the left if not program

---

data/vectorscope.effect
src/vectorscope.c

User can zoom-in and -out by rotating mouse wheel.
The center of the black point is adjusted so that the zoom is centered by the black point.

vectorscope: Accept mouse wheel to zoom

---

data/common.effect
data/vectorscope.effect
src/common.c
src/common.h
src/histogram.c
src/plugin-main.c
src/roi.c
src/vectorscope.c
src/waveform.c
src/zebra.c

Since the effects are cached in libobs, it is not necessary to have the global variables to hold the pointer to the effect file. All the global effect pointers are moved into the structures of the instances. Also separated RGB to YUV conversion effect to common.effect.

Move global effect pointer to each instance

---

.github/workflows/main.yml
CMakeLists.txt
cmake/ObsPluginHelpers.cmake
cmake/bundle/macos/Plugin-Info.plist.in
cmake/bundle/macos/entitlements.plist
installer/installer-macOS.pkgproj.in

Someone reported current plugin directory structure is not read by OBS 28.
https://twitter.com/kilinbox/status/1559542424761876480
This reverts commit 5c35802987a7753172b8f005af428f19c5196d2d.
And adjust packaging and notarization steps.

CI(macOS): Build bundle-type plugin package

---

.github/workflows/main.yml

- Build universal binary instead of arm64 for OBS 28
- Update packaging and codesign script
- Do not register signing identity for main branch CI

CI(macOS): generate universal binary package

---

data/locale/en-US.ini
doc/histogram.md
src/histogram.c

This PR implements
- Add disable option
Close #53

histogram: Implement graticule

---

.github/containers/fedora-common/build.sh
.github/containers/fedora36/Dockerfile
.github/containers/fedora37/Dockerfile
.github/workflows/docker-build.yml
ci/plugin.spec

This PR improves the build flow for RPM packages.
- Install Qt5 libraries to docker so that the action will be faster if the docker is cached.
- Set obs-studio required version is greater than or equal to the current obs-studio version.
- Release number in the spec file will be automatically set.

.github: Improve RPM package build flow for Fedora

---

src/roi.c

Initialize a mutex, which was missing.
The bug was introduced at 4e68dc7b70 "Implement pipeline to render". A crash was reported on Windows.
Not tested yet.

roi: Fix crash when creating an ROI source

---

src-obsstudio/properties-view.cpp
src/SurfaceEventFilter.hpp
src/scope-widget.cpp
src/scope-widget.hpp

When the dock is floating, `SurfaceAboutToBeDestroyed` event arrives earlier than `~ScopeWidget()`. Let's destroy the display context at the event.
On the other hand, if it's docked, `~ScopeWidget()` arrives earlier than `SurfaceAboutToBeDestroyed`. I need to remove the event filter not to access the released object from the surface event filter.

dock: Add a surface event filter to destroy display context

---

.github/workflows/main.yml
src/scope-dock-new-dialog.cpp
src/scope-dock.cpp
src/scope-dock.hpp
src/scope-widget.cpp
src/scope-widget.hpp

- src: Use `obs_frontend_add_dock_by_id`
- src: Remove legacy code for obs-studio 29 and earlier.
- .github: Use obs-studio-devel-action@v2
- .github: Drop supporting obs-studio 27, 28, 29.

Drop supporting OBS 29 and earlier

---

src/common.c

At one of the rendering stages, it was missing to clear the texture. Due to this, the previous texture appeared in the views on the dock.
Fixes #100.
OS: Fedora 39

Clear texture before rendering to RGB and YUV

---

src-obsstudio/qt-wrappers.hpp
src/obsgui-helper.hpp

This PR includes these changes.
- Removed deprecated enum value `OBS_NIX_PLATFORM_X11_GLX`.
- Removed unused function declaration.
Fix #106.
Confirmed the build flow succeeded on Fedora 40.

Update QTToGSWindow for OBS Studio 31

---

.github/workflows/docker-build.yml

- Added Fedora 41 RPM build flow
- Dropped Fedora 39 RPM build flow
Tested `obs-studio-plugin-color-monitor-0.8.2-8.fc41.x86_64.rpm` generated by the CI.

.github(Fedora): Add RPM build flow for Fedora 41 and remove 39
