norihiro/obs-color-monitor

ci/macos/package-dmg.json.template, ci/macos/package-macos.sh
to make installation flow simple
=> ci(macos): create a symlink to plugins directory

CMakeLists.txt, src/histogram.c, src/plugin-macros.h.in, src/vectorscope.c, src/waveform.c
To enable this, add an option `-D ENABLE_PROFILE=ON` to cmake.
=> all: added profiler as an option

CMakeLists.txt, README.md, ci/linux/install-dependencies-ubuntu.sh, src-obsstudio/combobox-ignorewheel.cpp, src-obsstudio/combobox-ignorewheel.hpp, src-obsstudio/double-slider.cpp, src-obsstudio/double-slider.hpp, src-obsstudio/properties-view.cpp, src-obsstudio/properties-view.hpp, src-obsstudio/qt-wrappers.cpp, src-obsstudio/qt-wrappers.hpp, src-obsstudio/slider-ignorewheel.cpp, src-obsstudio/slider-ignorewheel.hpp, src-obsstudio/spinbox-ignorewheel.cpp, src-obsstudio/spinbox-ignorewheel.hpp, src-obsstudio/vertical-scroll-area.cpp, src-obsstudio/vertical-scroll-area.hpp, src/obsgui-helper.hpp, src/plugin-main.c, src/scope-dock.cpp, src/scope-dock.hpp, src/scope-widget-properties.cpp, src/scope-widget-properties.hpp, src/scope-widget.cpp, src/scope-widget.hpp
=> Implement dock

CMakeLists.txt, azure-pipelines.yml, ci/linux/build-ubuntu.sh, ci/linux/package-ubuntu.sh, ci/macos/build-macos.sh, ci/macos/package-macos.sh, ci/windows/package-windows.cmd, ci/windows/prepare-obs-windows.cmd, ci/windows/prepare-windows.cmd
This change is made by referring the template at
https://github.com/norihiro/obs-plugintemplate/commit/c964bfd06de54e0d9eb5873e40e0d14c5ecfd5c3
=> ci: revise scripts to follow c964bfd06

src/scope-dock.cpp, src/scope-widget.cpp
=> Dock bugfix

azure-pipelines.yml, ci/macos/package-macos.sh, ci/windows/prepare-obs-windows.cmd, ci/windows/prepare-windows.cmd
This PR merges my template including macOS notarization flow.
=> Macos notarization

doc/dock.md, src/common.c, src/roi.c, src/roi.h
=> roi: interleave stage-surface

doc/dock.md, src/scope-dock.cpp
=> Dock bugfix default

data/histogram.effect, data/vectorscope.effect, data/waveform.effect, doc/histogram.md, doc/waveform.md, src/common.c, src/common.h, src/histogram.c, src/roi.c, src/roi.h, src/vectorscope.c, src/waveform.c
=> waveform: Add components property to select YUV

src/common-cpp.cc, src/histogram.c, src/roi.c, src/scope-dock.cpp, src/scope-widget.cpp, src/waveform.c
=> Fix warnings in Windows build

azure-pipelines.yml, ci/macos/build-macos.sh
=> ci(macos): set CMAKE_OSX_DEPLOYMENT_TARGET=10.13

azure-pipelines.yml
=> ci(macos): Upgrade macOS 10.14 to 10.15

CMakeLists.txt, data/zebra.effect, src/common.c, src/common.h, src/plugin-macros.h.in, src/plugin-main.c, src/scope-widget.cpp, src/scope-widget.hpp, src/zebra.c
=> Implement zebra

ci/windows/package-windows.cmd
=> CI: Leave SHA1 hash for releasing packages in a log

README.md, data/falsecolor.effect, doc/falsecolor.md, src/plugin-main.c, src/scope-widget.cpp, src/scope-widget.hpp, src/zebra.c
This is a new implementation of false color as a source and a filter, and adding it to the dock.
TODO:
Generic checklist
=> Falsecolor

src/scope-widget.cpp, src/vectorscope.c
- dock: Fix crash on Qt6
- dock: Fix mouse position on high DPI display
- Fix several warnings
=> Qt6 several bug fixes

.github/workflows/main.yml, CMakeLists.txt, cmake/ObsPluginHelpers.cmake, installer/installer-macOS.pkgproj.in
- CI(Linux): generate dependencies automatically
- cmake: Remove unused variable `MACOSX_PLUGIN_*`
- cmake: Remove `PLUGIN_HEADERS`
- CI(macOS): Change UUID
- CI(macOS): Fix change-rpath.sh
- CI(macOS): Do not notarize without tags
- CI(macOS): Use norihiro/macos-notarize-action@v1 instead of @v1-beta
=> CI: General changes for CI script

.github/containers/fedora-common/build.sh, .github/containers/fedora36/Dockerfile, .github/containers/fedora36/build.sh, .github/containers/fedora37/Dockerfile, .github/containers/fedora37/build.sh, .github/workflows/docker-build.yml, ci/plugin.spec
There is a third-party OBS Studio in RPM Fusion.
This PR adds a build flow to generate RPM packages for Fedora 35 and 36.
=> .github: Add docker build flow for Fedora 35 and 36

README.md
Currently, there are five sources.
=> Fix number of sources

CMakeLists.txt, src/ScopeWidgetInteractiveEventFilter.cpp, src/ScopeWidgetInteractiveEventFilter.hpp, src/SurfaceEventFilter.cpp, src/SurfaceEventFilter.hpp, src/scope-widget.cpp, src/scope-widget.hpp
Moves the event filter implementations to separated files.
Also fixes memory leaks of the event filters.
=> Rewrite event filters

README.md, doc/global_config.md, src/histogram.c, src/plugin-main.c, src/roi.c, src/vectorscope.c, src/waveform.c, src/zebra.c
This PR adds global config options to hide source and filter types.
OS: Fedora 37
=> Disable source and filter types from the add menu

src/scope-widget.cpp
As the activities of #86, the key was added. However, the labels are too small when the dock was small.
To easily see the key and it's labels, add a menu item that opens a projector window of the right-clicked scope.
Tested on Fedora 39.
=> dock: Add menu item to open projector

src/roi.c
CodeFactor suggested to reduce the number of lines in a function.
OS: Fedora 39
Open the scope dock and try dragging on the ROI window.
=> src (ROI): Reduce long functions

CMakeLists.txt, cmake/ObsPluginHelpers.cmake
Add an `option` command to set the Qt version to 6.
CI will test.
=> cmake: Add default settings for Qt version

.gitignore, CMakeLists.txt
Create `.gitignore` file by cmake so that the build directory will be ignored.
Tested on macOS with `build` directory.
=> Create .gitignore on build directory by cmake

src/scope-widget.cpp
The handlers of `visibleChanged` and `screenChanged` are copied from exeldro/obs-source-dock.
https://github.com/exeldro/obs-source-dock/blob/58ff5204ef47085d055cb20520003a103140e28b/qt-display.cpp#L107-L132
On macOS, after the scope dock window was docked to or undocked from the main window, the display was vanished.
Environment: OBS Studio 31.0.0-beta3-7, macOS.
=> dock: Fix display not updated when docked and un-docked on macOS

.github/workflows/clang-format.yml, src/vectorscope.c
Upgrade clang-format version from 13 to 18.
Checked `git diff -w` does not show any changes in the modified source file.
CI will test.
=> .github: Upgrade clang-format version to 18

.github/workflows/docker-build.yml
- Added RPM build flow for Fedora 42
- Removed that for Fedora 40
CI will test
=> .github(Fedora): Add RPM build flow for Fedora 42 and remove 40
